import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-1 min-h-screen  flex-col items-center justify-between p-24">
          <div
            style={{ width: 400, height: 300 }}
            className="bg-offwhite rounded-xl p-6"
          >
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
