[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
